### ISSUE TITLE
check thresholds 

### ISSUE THREAD

**Issue by timm** [ai-se/XTREE-FSE#1]
we really could use n oracles saying that XYZ thresholds matter... and we show that they do not. lucas has some thresholds in "code-smells2". and you talked BIG in december about some book with thresholds. and there STILL remains the issue of what thresholds are shown in the sonarqube package so what is the story with those thresholds? do they not exist? they DO exist and you have just not written them down? what?

so IF those thresholds exist, then please offer a table listing them and how XTREE's recommendations are different.

ELSE tell me why they keep disappearing

**Comment by rahlk** [comment]
Hey Dr. M,
Over Christmas, I tried reading the book. Too verbose, it didn't have any thresholds we could use. So I looked at tools that detect code smells. They only use as few CK metrics, and we don't change them. But I've added them in the paper in the results section, see figure 8:
![image](https://cloud.githubusercontent.com/assets/1433964/13383148/ed2dc124-de52-11e5-8908-2bfb5ddcb588.png)

I've read all the references you've been sending me. No one mentions numbers, they only say address this, address that. So on...

R http://rkrsn.us/Resume/

**Comment by timm** [comment]
RE resume http://rkrsn.us/Resume/>: you need to leave space for 5 lines at the top where the resume can be tuned to where ever you are sending it. As a space filler, add five lines about 
- My career goal is  to better understand the nature of human and artificial intelligence symbiosis- its practical applications  and drawbacks--  with a particular focus on what tools can most enhance the human/machine collaborative experience

or some such b.s.

**Comment by timm** [comment]
looks good. share latex is not behaving so i cant read the paper or look at https://cloud.githubusercontent.com/assets/1433964/13383148/ed2dc124-de52-11e5-8908-2bfb5ddcb588.png. the key thing here is to make the claim that PRIOR work suggested XYZ was important and we can learn instead that certain local changes (proposed by xtree) can do better than that.

**Comment by rahlk** [comment]
Ah.. I see what you mean, I'll update the experiments sections accordingly.

**Comment by rahlk** [comment]
See #7
