### ISSUE TITLE
need much more on comparisons

### ISSUE THREAD

**Issue by timm** [ai-se/XTREE-FSE#5]
on XYX says that ABC is a good change but XTREES says that that change falls outisde the space of useful results

i'm goign to cut the XTREE section down to around 3 pages so out results section can list all those "it does not matter" results.

you mission: find all those ranges and compare them to XTREE's proposed ranges

t

**Comment by rahlk** [comment]
Found a TSE paper with just what we need! They don't have all the metrics, but they have everything we need. 
![image](https://cloud.githubusercontent.com/assets/1433964/13413673/4f59e6bc-df1a-11e5-872e-c7f12405901c.png)

![image](https://cloud.githubusercontent.com/assets/1433964/13413678/5b5aab68-df1a-11e5-9e1c-361257b8e814.png)

**Comment by rahlk** [comment]
Done see #7
